/**
 * Code Generator — Takes a ProjectSpec and generates Solidity contract code,
 * Foundry deploy scripts, and frontend config scaffolding.
 *
 * Uses Handlebars templates from the templates/ directory.
 */

import Handlebars from 'handlebars';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { ProjectSpec, ContractSpec } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// In production (dist/generator.js), templates are at dist/templates/
// In development (src/generator.ts), templates are at src/templates/
// Both resolve to __dirname/templates since we copy .hbs files during build
const TEMPLATES_DIR = join(__dirname, 'templates');

// --- Template Loading & Compilation ---

const templateCache = new Map<string, HandlebarsTemplateDelegate>();

function loadTemplate(name: string): HandlebarsTemplateDelegate {
  const cached = templateCache.get(name);
  if (cached) return cached;

  const filePath = join(TEMPLATES_DIR, `${name}.hbs`);
  let source: string;
  try {
    source = readFileSync(filePath, 'utf-8');
  } catch (err) {
    throw new Error(`Template "${name}" not found at ${filePath}: ${(err as Error).message}`);
  }

  const template = Handlebars.compile(source, { noEscape: true });
  templateCache.set(name, template);
  return template;
}

// --- Handlebars Helpers ---

Handlebars.registerHelper('eq', (a: unknown, b: unknown) => a === b);
Handlebars.registerHelper('neq', (a: unknown, b: unknown) => a !== b);
Handlebars.registerHelper('or', (a: unknown, b: unknown) => !!a || !!b);
Handlebars.registerHelper('uppercase', (str: string) => (str ?? '').toUpperCase());

// --- Code Generation ---

/**
 * Generate all contract source files from a ProjectSpec.
 * Returns a Map of relative file path → file content.
 */
export function generateContracts(spec: ProjectSpec): Map<string, string> {
  const files = new Map<string, string>();

  for (const contract of spec.contracts) {
    const contractFiles = generateSingleContract(contract, spec);
    for (const [path, content] of contractFiles) {
      files.set(path, content);
    }
  }

  // Always generate the deploy script
  files.set('script/Deploy.s.sol', generateDeployScript(spec));

  // Generate frontend config stub
  files.set('frontend/src/config.ts', generateFrontendConfig(spec));

  // Generate foundry.toml
  files.set('foundry.toml', generateFoundryConfig(spec));

  return files;
}

function generateSingleContract(
  contract: ContractSpec,
  spec: ProjectSpec,
): Map<string, string> {
  const files = new Map<string, string>();

  const template = loadTemplate(contract.template);
  const source = template({
    ...contract.params,
    contractName: contract.name,
    projectType: spec.type,
    chain: spec.chain,
  });
  files.set(`src/${contract.name}.sol`, source);

  return files;
}

function generateDeployScript(spec: ProjectSpec): string {
  const imports: string[] = [];
  const deploys: string[] = [];

  for (const contract of spec.contracts) {
    imports.push(`import {${contract.name}} from "../src/${contract.name}.sol";`);

    const constructorArgs = buildConstructorArgs(contract);
    deploys.push(
      `    vm.startBroadcast();\n` +
      `    ${contract.name} ${toCamelCase(contract.name)} = new ${contract.name}(${constructorArgs});\n` +
      `    console.log("${contract.name} deployed at:", address(${toCamelCase(contract.name)}));\n` +
      `    vm.stopBroadcast();`,
    );
  }

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Script.sol";
${imports.join('\n')}

contract DeployScript is Script {
    function run() external {
${deploys.join('\n\n')}
    }
}
`;
}

function buildConstructorArgs(contract: ContractSpec): string {
  const p = contract.params;
  switch (contract.template) {
    case 'erc20': {
      const args: string[] = [];
      if (p.tokenName) args.push(`"${p.tokenName}"`);
      if (p.tokenSymbol) args.push(`"${p.tokenSymbol}"`);
      return args.join(', ');
    }
    default:
      return '';
  }
}

function generateFrontendConfig(spec: ProjectSpec): string {
  const placeholders = spec.contracts.map((c) => ({
    name: c.name,
    address: '0x0000000000000000000000000000000000000000',
  }));

  return `// Auto-generated by ChainForge — update addresses after deployment
export const chainId = ${getChainId(spec.chain)};
export const chainName = "${spec.chain}";
export const projectType = "${spec.type}";

export const contracts = {
${placeholders.map((p) => `  ${toCamelCase(p.name)}: "${p.address}",`).join('\n')}
} as const;

export const features = ${JSON.stringify(spec.features, null, 2)};
`;
}

function generateFoundryConfig(spec: ProjectSpec): string {
  const solVersion = '0.8.24';
  return `[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "${solVersion}"
optimizer = true
optimizer_runs = 200

[profile.default.rpc_endpoints]
${spec.chain} = "${getRpcUrl(spec.chain)}"

[etherscan]
${spec.chain} = { key = "\${ETHERSCAN_API_KEY}" }
`;
}

// --- Helpers ---

function toCamelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function getChainId(chain: string): number {
  const ids: Record<string, number> = {
    ethereum: 1,
    base: 8453,
    arbitrum: 42161,
    polygon: 137,
    bsc: 56,
    sepolia: 11155111,
  };
  return ids[chain] ?? 11155111;
}

function getRpcUrl(chain: string): string {
  const urls: Record<string, string> = {
    ethereum: 'https://eth.llamarpc.com',
    base: 'https://mainnet.base.org',
    arbitrum: 'https://arb1.arbitrum.io/rpc',
    polygon: 'https://polygon-rpc.com',
    bsc: 'https://bsc-dataseed.bnbchain.org',
    sepolia: 'https://rpc.sepolia.org',
  };
  return urls[chain] ?? 'https://rpc.sepolia.org';
}

export { getChainId, getRpcUrl };
