/**
 * Prompt Parser — Uses Claude API to extract structured project requirements
 * from a natural language description.
 *
 * Supports English and Indonesian (Bahasa Indonesia) prompts.
 */

import Anthropic from '@anthropic-ai/sdk';
import { z } from 'zod';
import dotenv from 'dotenv';
import type { ProjectSpec } from './types.js';

dotenv.config({ path: new URL('../../.env', import.meta.url).pathname });

// --- Zod Schemas for validation ---

const ProjectTypeSchema = z.enum([
  'token', 'nft', 'dex', 'staking', 'dao', 'marketplace',
]);

const ChainSchema = z.enum([
  'ethereum', 'base', 'arbitrum', 'polygon', 'bsc', 'sepolia',
]);

const ContractSpecSchema = z.object({
  name: z.string().min(1),
  type: z.string().min(1),
  params: z.record(z.any()),
  template: z.string().min(1),
});

const FrontendSpecSchema = z.object({
  pages: z.array(z.string()).min(1),
  theme: z.string().default('dark'),
  walletConnect: z.boolean().default(true),
});

const ProjectSpecSchema = z.object({
  name: z.string().min(1).max(100),
  description: z.string().min(1).max(500),
  type: ProjectTypeSchema,
  chain: ChainSchema.default('sepolia'),
  contracts: z.array(ContractSpecSchema).min(1),
  frontend: FrontendSpecSchema,
  features: z.array(z.string()),
});

// --- System prompt for Claude ---

const SYSTEM_PROMPT = `You are ChainForge's AI parser. Your job is to extract a structured blockchain project specification from a user's natural language description.

The user may write in English or Indonesian (Bahasa Indonesia). Understand both languages equally well.

You MUST return a single JSON object matching this exact schema:
{
  "name": "string — project name (kebab-case or PascalCase)",
  "description": "string — one-line description",
  "type": "token" | "nft" | "dex" | "staking" | "dao" | "marketplace",
  "chain": "ethereum" | "base" | "arbitrum" | "polygon" | "bsc" | "sepolia",
  "contracts": [
    {
      "name": "string — contract name (PascalCase)",
      "type": "string — e.g. ERC20, ERC721, custom",
      "params": { },
      "template": "string — template file name, e.g. erc20"
    }
  ],
  "frontend": {
    "pages": ["string — page names like Home, Mint, Dashboard"],
    "theme": "dark" | "light" | "auto",
    "walletConnect": true | false
  },
  "features": ["string — list of features like mintable, burnable, pausable, staking, governance"]
}

Rules:
- If the user doesn't specify a chain, default to "sepolia" (testnet).
- If the user doesn't specify features, include sensible defaults based on the project type.
- For token projects, default to a standard ERC-20 with name, symbol, and supply.
- For NFT projects, default to ERC-721 with minting.
- Always generate at least one contract.
- Always include at least a "Home" page in frontend.pages.
- Return ONLY valid JSON. No markdown fences, no explanations, no commentary.

Common Indonesian mappings:
- "token" / "koin" / "kripto" → type: "token"
- "NFT" / "koleksi" / "seni digital" → type: "nft"
- "bursa" / "tukar" / "swap" / "DEX" → type: "dex"
- "staking" / "stake" / "taruhan" → type: "staking"
- "DAO" / "organisasi" / "governance" / "voting" → type: "dao"
- "marketplace" / "pasar" / "toko" → type: "marketplace"`;

// --- Default fallback spec ---

const DEFAULT_PROJECT_SPEC: ProjectSpec = {
  name: 'my-project',
  description: 'A blockchain project generated by ChainForge',
  type: 'token',
  chain: 'sepolia',
  contracts: [
    {
      name: 'MyToken',
      type: 'ERC20',
      params: {
        tokenName: 'My Token',
        tokenSymbol: 'MTK',
        maxSupply: 1000000,
        mintable: true,
        burnable: false,
        pausable: false,
        snapshotEnabled: false,
      },
      template: 'erc20',
    },
  ],
  frontend: {
    pages: ['Home', 'Dashboard'],
    theme: 'dark',
    walletConnect: true,
  },
  features: ['mintable'],
};

// --- Parser function ---

/**
 * Parse a natural language prompt into a structured ProjectSpec using Claude.
 * Handles both English and Indonesian prompts.
 *
 * @param prompt - The user's natural language description
 * @returns A validated ProjectSpec object
 * @throws If the API key is missing, the API fails, or the response is invalid
 */
export async function parsePrompt(prompt: string): Promise<ProjectSpec> {
  if (!prompt || prompt.trim().length === 0) {
    throw new Error('Prompt cannot be empty');
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error(
      'ANTHROPIC_API_KEY not found. Set it in .env file at the project root or as an environment variable.',
    );
  }

  const client = new Anthropic({ apiKey });

  try {
    const message = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2048,
      temperature: 0.2,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    // Extract text content from the response
    const textBlock = message.content.find((block) => block.type === 'text');
    if (!textBlock || textBlock.type !== 'text') {
      throw new Error('Claude returned no text content');
    }

    let rawText = textBlock.text.trim();

    // Strip markdown code fences if present (fallback safety)
    rawText = rawText.replace(/^```(?:json)?\s*\n?/m, '').replace(/\n?```\s*$/m, '');

    let parsed: unknown;
    try {
      parsed = JSON.parse(rawText);
    } catch {
      throw new Error(
        `Claude returned invalid JSON. Raw output:\n${rawText.slice(0, 500)}`,
      );
    }

    // Validate with Zod
    const result = ProjectSpecSchema.safeParse(parsed);
    if (!result.success) {
      const issues = result.error.issues
        .map((i) => `${i.path.join('.')}: ${i.message}`)
        .join('\n');
      throw new Error(
        `Parsed spec failed validation:\n${issues}\n\nRaw JSON:\n${rawText.slice(0, 500)}`,
      );
    }

    return result.data as ProjectSpec;
  } catch (err) {
    if (err instanceof Anthropic.APIError) {
      throw new Error(
        `Anthropic API error (${err.status}): ${err.message}`,
      );
    }
    throw err;
  }
}

/**
 * Parse prompt with graceful fallback to defaults if the AI call fails.
 * Useful for non-critical paths where a reasonable default is acceptable.
 */
export async function parsePromptSafe(prompt: string): Promise<ProjectSpec> {
  try {
    return await parsePrompt(prompt);
  } catch (err) {
    console.warn('⚠️  AI parsing failed, using defaults:', (err as Error).message);
    return {
      ...DEFAULT_PROJECT_SPEC,
      name: extractProjectName(prompt) ?? DEFAULT_PROJECT_SPEC.name,
      description: prompt.slice(0, 200),
    };
  }
}

/**
 * Try to extract a project name from the prompt text heuristically.
 */
function extractProjectName(prompt: string): string | null {
  const patterns = [
    /["']([a-zA-Z][\w-]+)["']/,
    /(?:called|named|nama)\s+["']?([a-zA-Z][\w-]+)["']?/i,
  ];
  for (const pat of patterns) {
    const match = prompt.match(pat);
    if (match?.[1]) return match[1];
  }
  return null;
}
