import { ProjectSpec } from '@/types'

export function generateERC20(spec: ProjectSpec): string {
  const hasMint = spec.features.includes('mintable')
  const hasBurn = spec.features.includes('burnable')
  const hasPause = spec.features.includes('pausable')
  const hasPermit = spec.features.includes('permit')
  const hasVotes = spec.features.includes('votes')
  const hasCapped = spec.features.includes('capped')
  
  const imports = [
    '"@openzeppelin/contracts/token/ERC20/ERC20.sol"',
    '"@openzeppelin/contracts/access/Ownable.sol"',
    hasBurn ? '"@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol"' : null,
    hasPause ? '"@openzeppelin/contracts/security/Pausable.sol"' : null,
    hasPermit ? '"@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol"' : null,
    hasVotes ? '"@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol"' : null,
    hasCapped ? '"@openzeppelin/contracts/token/ERC20/extensions/ERC20Capped.sol"' : null,
  ].filter(Boolean)

  const parentContracts = [
    'ERC20',
    'Ownable',
    hasBurn ? 'ERC20Burnable' : null,
    hasPause ? 'Pausable' : null,
    hasPermit ? 'ERC20Permit' : null,
    hasVotes ? 'ERC20Votes' : null,
    hasCapped ? 'ERC20Capped' : null,
  ].filter(Boolean)

  const constructorParams = hasCapped
    ? `ERC20("${spec.name}", "${spec.symbol}")\n        ERC20Permit("${spec.name}")\n        ERC20Capped(${spec.params.supply} * 10 ** decimals())`
    : `ERC20("${spec.name}", "${spec.symbol}")\n        Ownable(msg.sender)${hasPermit ? `\n        ERC20Permit("${spec.name}")` : ''}`

  const constructorBody = `_mint(msg.sender, ${spec.params.supply} * 10 ** decimals());`

  const mintFunction = hasMint ? `
    /**
     * @dev Mints new tokens to the specified address.
     * @param to The address to mint tokens to.
     * @param amount The amount of tokens to mint.
     */
    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }` : ''

  const pauseFunctions = hasPause ? `
    /**
     * @dev Pauses all token transfers.
     */
    function pause() public onlyOwner {
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     */
    function unpause() public onlyOwner {
        _unpause();
    }

    function _update(address from, address to, uint256 value)
        internal
        override(ERC20, Pausable${hasVotes ? ', ERC20Votes' : ''})
    {
        super._update(from, to, value);
    }` : ''

  const voteOverrides = hasVotes ? `
    function nonces(address owner)
        public
        view
        override(ERC20Permit, Nonces)
        returns (uint256)
    {
        return super.nonces(owner);
    }` : ''

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

${imports.map(i => `import ${i};`).join('\n')}

/**
 * @title ${spec.name}
 * @author BlockPilot (https://blockpilot.ai)
 * @notice ERC-20 token with ${spec.features.join(', ')} features
 * @dev Generated by BlockPilot AI — verify before mainnet deployment
 */
contract ${spec.name.replace(/\s+/g, '')} is ${parentContracts.join(', ')} {
    /**
     * @dev Initializes the token with name, symbol, and initial supply.
     * @param initialSupply The number of tokens to mint to the deployer
     */
    constructor(uint256 initialSupply)
        ${constructorParams}
    {
        ${constructorBody}
    }
${mintFunction}
${pauseFunctions}
${voteOverrides}
}
`
}
