import { ProjectSpec } from '@/types'

export function generateERC721(spec: ProjectSpec): string {
  const maxSupply = String(spec.params.maxSupply || spec.params.supply || '10000')
  const mintPrice = String(spec.params.mintPrice || '0.01')
  
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/interfaces/IERC2981.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title ${spec.name}
 * @author BlockPilot (https://blockpilot.ai)
 * @notice ERC-721 NFT Collection with ${spec.features.join(', ')}
 * @dev Generated by BlockPilot AI — verify before mainnet deployment
 */
contract ${spec.name.replace(/\s+/g, '')} is ERC721, ERC721Enumerable, ERC721URIStorage, Ownable, IERC2981 {
    using Strings for uint256;

    uint256 private _nextTokenId;
    uint256 public constant MAX_SUPPLY = ${maxSupply};
    uint256 public mintPrice = ${mintPrice} ether;
    string private _baseTokenURI;
    bool public revealed = false;
    string public notRevealedURI;

    // Royalty info
    address private _royaltyRecipient;
    uint256 private _royaltyBps = 500; // 5%

    constructor(
        string memory name_,
        string memory symbol_,
        string memory baseURI_,
        address royaltyRecipient_
    ) ERC721(name_, symbol_) Ownable(msg.sender) {
        _baseTokenURI = baseURI_;
        _royaltyRecipient = royaltyRecipient_;
    }

    /**
     * @dev Mints a new NFT to the caller.
     */
    function mint(uint256 quantity) external payable {
        require(quantity > 0 && quantity <= 10, "Invalid quantity");
        require(_nextTokenId + quantity <= MAX_SUPPLY, "Max supply reached");
        require(msg.value >= mintPrice * quantity, "Insufficient payment");

        for (uint256 i = 0; i < quantity; i++) {
            uint256 tokenId = _nextTokenId++;
            _safeMint(msg.sender, tokenId);
        }
    }

    /**
     * @dev Owner mint — free, for airdrop/reserve.
     */
    function ownerMint(address to, uint256 quantity) external onlyOwner {
        require(_nextTokenId + quantity <= MAX_SUPPLY, "Max supply reached");
        for (uint256 i = 0; i < quantity; i++) {
            uint256 tokenId = _nextTokenId++;
            _safeMint(to, tokenId);
        }
    }

    /**
     * @dev Set the base URI for computing tokenURI.
     */
    function setBaseURI(string calldata baseURI_) external onlyOwner {
        _baseTokenURI = baseURI_;
    }

    /**
     * @dev Toggle reveal state.
     */
    function setRevealed(bool _revealed) external onlyOwner {
        revealed = _revealed;
    }

    /**
     * @dev Set not-revealed placeholder URI.
     */
    function setNotRevealedURI(string calldata _notRevealedURI) external onlyOwner {
        notRevealedURI = _notRevealedURI;
    }

    /**
     * @dev Set mint price.
     */
    function setMintPrice(uint256 _mintPrice) external onlyOwner {
        mintPrice = _mintPrice;
    }

    /**
     * @dev Set royalty info (ERC-2981).
     */
    function setRoyalty(address recipient, uint256 bps) external onlyOwner {
        require(bps <= 10000, "Invalid bps");
        _royaltyRecipient = recipient;
        _royaltyBps = bps;
    }

    /**
     * @dev Withdraw contract balance.
     */
    function withdraw() external onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "No balance");
        (bool success, ) = payable(owner()).call{value: balance}("");
        require(success, "Transfer failed");
    }

    // --- ERC-2981 ---
    function royaltyInfo(uint256, uint256 _salePrice)
        external
        view
        override
        returns (address receiver, uint256 royaltyAmount)
    {
        return (_royaltyRecipient, (_salePrice * _royaltyBps) / 10000);
    }

    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, ERC721Enumerable, ERC721URIStorage, IERC165)
        returns (bool)
    {
        return interfaceId == type(IERC2981).interfaceId || super.supportsInterface(interfaceId);
    }

    // --- Required overrides ---
    function _baseURI() internal view override returns (string memory) {
        if (!revealed && bytes(notRevealedURI).length > 0) {
            return notRevealedURI;
        }
        return _baseTokenURI;
    }

    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }

    function _update(address to, uint256 tokenId, address auth)
        internal
        override(ERC721, ERC721Enumerable)
        returns (address)
    {
        return super._update(to, tokenId, auth);
    }

    function _increaseBalance(address account, uint128 value)
        internal
        override(ERC721, ERC721Enumerable)
    {
        super._increaseBalance(account, value);
    }
}
`
}
